[package]
name = "py-polars"
version = "0.0.1"
authors = ["ritchie46 <ritchie46@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
polars = {path = "../polars", features = ["parquet", "simd", "parallel"]}
pyo3 = {version = "0.11", features = ["extension-module"] }
thiserror = "1.0.20"
numpy = "0.11"
ndarray = "0.13.1"
parquet = "1.0.1"


[lib]
name = "pypolars"
crate-type = ["cdylib"]


[package.metadata.maturin]
requires-dist = ["numpy"]