[package]
name = "py_polars"
version = "0.1.0"
authors = ["ritchie46 <ritchie46@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
polars = {path = "../polars"}
pyo3 = {version = "0.11.1", features = ["extension-module"] }
thiserror = "1.0.20"
numpy = "0.10.0"
ndarray = "0.13.1"


[lib]
name = "polars"
crate-type = ["cdylib"]


[package.metadata.maturin]
requires-dist = ["numpy"]