version: 2

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: py-polars/docs/source/conf.py

formats: all

# Optionally set the version of Python and requirements required to build your docs
python:
  version: 3.7
  install:
    - requirements: py-polars/docs.requirements.txt

