[workspace]

members = [
    "polars",
    "polars/polars-core",
    "polars/polars-io",
    "polars/polars-lazy",
    "polars/polars-arrow",
    "py-polars",
]

[profile.release]
codegen-units = 1

# This is ignored here; would be set in .cargo/config.toml.
# Should not be used when packaging
# target-cpu = "native"
lto = "fat"

#[profile.dev]
#opt-level = 1
