[package]
name = "polars"
version = "0.7.2"
authors = ["ritchie46 <ritchie46@gmail.com>"]
edition = "2018"
license = "MIT"
description = "DataFrame library"
repository = "https://github.com/ritchie46/polars"
readme = "../README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
pretty = ["prettytable-rs"]
simd = [] #["arrow/simd"]
docs = []
temporal = ["chrono"]
random = ["rand", "rand_distr"]
parallel = []
default = ["pretty", "docs", "temporal", "simd"]
lazy = []
# extra utilities for Utf8Chunked
strings = ["regex"]

[dependencies]
arrow = {version = "1.0.1", default_features = false}
thiserror = "^1.0.16"
num = "^0.2.1"
fnv = "^1.0.7"
itertools = "^0.9.0"
unsafe_unwrap = "^0.1.0"
rayon = "1.4"
prettytable-rs = { version="^0.8.0", features=["win_crlf"], optional = true, default_features = false}
chrono = {version = "^0.4.13", optional = true}
parquet = {version = "1", optional = true}
rand = {version = "0.7", optional = true}
rand_distr = {version = "0.3", optional = true}
ndarray = {version = "0.13", optional = true, default_features = false}
packed_simd_2 = "0.3.4"
regex = {version = "1.4", optional = true }
anyhow = "1.0"