[package]
name = "polars-arrow"
version = "0.14.8"
authors = ["ritchie46 <ritchie46@gmail.com>"]
edition = "2018"
license = "MIT"
description = "Arrow interfaces for Polars DataFrame library"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#arrow = { package = "arrow2", git = "https://github.com/jorgecarleitao/arrow2", rev = "decee2176fcdf4e985d9cc2607e6f3f996da805c", default-features = false }
arrow = { package = "arrow2", version = "0.2", default-features=false}
thiserror = "^1.0"
num = "^0.4"
