name: Build and test

on: push
jobs:
  test:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install latest Rust nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2020-11-12
          override: true
          components: rustfmt, clippy
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install maturin pytest black==20.8b1 pdoc3 numpy ghp-import pandas
      - name: Run formatting checks
        run: |
          cargo fmt -- --check
          black --check .
      - name: Run tests
        run: |
          cd polars && cargo test --all-features
          cd ../py-polars && ./tasks.sh build-run-tests && cd ..
      - name: deploy docs
        run: |
          cargo doc --no-deps --all-features --package polars \
          && echo '<meta http-equiv=refresh content=0;url=polars/index.html>' > target/doc/index.html && \
          pdoc --html py-polars/pypolars/ && \
          mv html/pypolars target/doc/pypolars && \
          ghp-import -n target/doc && \
          git push -qf https://${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git gh-pages
