name: Lint global

on:
  pull_request:
    paths:
      - ['**.md', '**.toml']  # This workflow currently only lints markdown and TOML files
      - '.github/workflows/lint-global.yaml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dprint/check@v2.1
