name: Windows tests

on: push
jobs:
  test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install latest Rust nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2020-11-12
          override: true
      - name: Run tests
        run: |
          cd polars && cargo test
          cd ../py-polars && ./tasks.sh build-run-tests
